import "./assets/globals.css";
import Header from "./components/header";
import localFont from "next/font/local";

// Google fonts'dan font çekme
import { Poppins } from "next/font/google";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400"],
});

// Local font tanımlama
export const geistSans = localFont({
  src: "./assets/fonts/GeistVF.woff",
  variable: "--font-geist",
  weight: "100 900",
});

export const jedi = localFont({
  src: "./assets/fonts/Starjedi.ttf",
  variable: "--font-jedi",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={poppins.style}
        className={`${poppins.className} antialiased`}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
