const ActionTypes = {
  GENRE_LOADING: "GENRE_LOADING",
  GENRE_ERROR: "GENRE_ERROR",
  GENRE_SUCCESS: "GENRE_SUCCESS",

  FAV_LOADING: "FAV_LOADING",
  FAV_ERROR: "FAV_ERROR",
  FAV_SUCCESS: "FAV_SUCCESS",

  ADD_TO_FAV: "ADD_TO_FAV",
  REMOVE_FAV: "REMOVE_FAV",
};

export default ActionTypes;
