const ActionTypes = {
  REST_LOADING: "REST_PENDING",
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",

  CART_LOADING: "CART_LOADING",
  CART_SUCCESS: "CART_SUCCESS",
  CART_ERROR: "CART_ERROR",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
};

export default ActionTypes;
